### PR TITLE
Add app skeleton 

### PR DESCRIPTION
**Pull request by que-sara-sara**
- create react app using `react-native init`
- add eslint, prettier, flow and babel (we'll need to strip flow types using babel). I'm using flow at work, and it would be cool to use it on this project too. if y'all have an issue with that, we should discuss. if we are going to use it, we should use it from the get-go, or it's going to be annoying to have a lot of undefined types. we can talk about some best practices that i'm learning from work too :)
- file structure: i didn't add this yet, mostly because i'm not sure how things will be structured. The next person who starts actually building in this probably will have a better idea of how things should look. I also can ask some react-native peeps at my office if we want some guidance there.

Also, the only files worth looking at are probably `index.js` and `App.jsx` to get a sense of how the app is started up, `package.json`, and `.eslintrc.js`

### CODE REVIEW

**Review by kenzable — COMMENTED** [review]
A few things:
- It seems like there's over 5,000 files now committed in this repo, and a lot of them are binary files. Would it be possible to ask your coworkers who have experience with React Native if it's really necessary to commit these things into our codebase? I'm wondering if some of them can just be imported in a build step before publishing. 
- Looks like the .DS_Store got committed accidentally (even though it's in the .git-ignore, hmmm)
- I'm in favor of ditching yarn.lock in favor of the default supported lockfile from npm

**Comment by que-sara-sara** [comment]
@kenzable thanks for that catch. I fixed that issue. a lot of files somehow bypassed gitignore, so i cleaned that up.
- i'm currently using yarn, since we're in fb land. would you rather move forward with npm instead? I don't really care, just would like to stay consistent. If we're using yarn, we shouldn't be committed the npm lockfile.

**Comment by kenzable** [comment]
@kaleidoscope82 I like the idea of just sticking to npm since that's one less dependency to have in our project. Also, now that you can do npm ci for install I think it's comparable in speed to yarn?

**Review by kenzable — APPROVED** [review]
Good 2 Go!

**Pull request merged**
